language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
env:
    - DJANGO_PACKAGE="Django>=1.8,<1.9"
    - DJANGO_PACKAGE="Django==1.11"
install: pip install -r requirements-test.txt $DJANGO_PACKAGE
script: PYTHONPATH=. DJANGO_SETTINGS_MODULE=example.settings django-admin test
notifications:
    email:
        - james.p.turk@gmail.com
