# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplekeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='quota_period',
            field=models.CharField(choices=[('d', 'daily'), ('m', 'monthly')], max_length=1),
        ),
    ]
