# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplekeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='usage',
            field=models.TextField(blank=True, verbose_name='Intended Usage'),
        ),
        migrations.AddField(
            model_name='key',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
